# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Stanley Idesis..."
email: stan.idesis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stanley Idesis is here to rock your world, blow your mind,
  save your soul, and have you back home by ten. Enter, but please
  take off your shoes first because we like to keep things clean here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stanleyidesis.com" # the base hostname & protocol for your site
rss: "/feed.xml"
permalink: pretty

# Variables
owner: "Stanley Idesis"

# Social
twitter_username: sisedi
github_username: stanidesis
facebook_username: levit.natan
instagram_username: sisedi
medium_username: sisedi
youtube_username: stanidesis
google_plus_username: StanIdesis
linkedin_username: stanleyidesis

base_twitter: "https://twitter.com/$s"
base_github: "https://github.com/$s"
base_facebook: "https://www.facebook.com/$s"
base_instagram: "https://instagram.com/$s/"
base_medium: "https://medium.com/@$s"
base_youtube: "https://www.youtube.com/user/$s/featured"
base_google_plus: "https://plus.google.com/u/1/+$s/"
base_linkedin: "https://www.linkedin.com/in/$s"


# Build settings
markdown: kramdown

highlighter: rouge

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "README.md"
  ]

gems: [
  jekyll-paginate
  ]

sass:
  style: compressed

# Outputting
timezone: America/Los_Angeles

# Instagram
INSTAGRAM_USER_ID:  "182831931"
TEMP_INSTAGRAM_API_KEY: "467ede5a6b9b48ae8e03f4e2582aeeb3"
INSTAGRAM_API_KEY:  "34aca56159d545e693674ccc1560dce3"
