# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

environment: prod
name: "Stanley Idesis: Content Strategist, Author, & Gift From Below"
description: "Congratulations are in order, visitor, because you have just stumbled across the greatest website description on Earth [citation needed]. What makes Stanley so great? His boundless humility, of course."
email: stan.idesis@gmail.com
url: https://www.stanleyidesis.com # the base hostname & protocol for your site, e.g.  http://example.com
# All 3 Required for Blog Postings
logo_url: "/mstile-144x144.png"
logo_width: "144"
logo_height: "144"
rss: "/feed.xml"
twitter_username: stanleyidesis
github_username:  stanidesis

# Build settings
markdown: kramdown

# Outputting
timezone: America/Chicago

collections_dir: collections

collections:
  categories:
  books:
  posts:
  works:
  work-clients:
  work-roles:
  work-topics:
  work-types:
  courses:
    output: true
    permalink: /:collection/:title

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]

toc:
  max_level: 3

# Google Analytics Constants
ga:
  hit-types:
    social: "social"
  social-networks:
    facebook: "Facebook"
    twitter: "Twitter"
    linkedin: "LinkedIn"
    email: "Email"
  categories:
    book-purchase-intent: "Outbound Link (Book)"
    course-purchase-intent: "Outbound Link (Course)"
    course-skillshare-intent: "Outbound Link (Skillshare)"
    exit-popup: "Exit Popup"
    post-cta: "Post CTA"
    save-resource: "Save Resource"
    playback-resource: "Playback Resource"
    share-resource: "Share Resource"
    resource: "Resource"
  actions:
    click: "click"
  labels:
    pdf: "pdf"
    epub: "epub"
    mobi: "mobi"
    mp3: "mp3"
    play: "play"
    pause: "pause"
    rewind: "rewind"
    fast-forward: "fast-forward"
    finished: "finished"
    show-nav: "show nav"
    hide-nav: "hide nav"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - firebase.json
  - package-lock.json
  - package.json
  - README.md
